nome = str(input('Diga o seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em letras maiúsculas é {} '.format(nome.upper()))
print('Seu nome em letras minúsculas é {} '.format(nome.lower()))
print('Seu nome ao todo tem {} letras.' .format(len(nome) - nome.count(' ')))
dividido = nome.split()
print('Seu primeiro nome tem {} letras' .format(len(dividido[0])))
